export const services = [
  {
    id: "development",
    iconKey: "laptop-code",
    title: "Développement & Solutions Digitales",
    description: "Applications web, mobiles et plateformes sur-mesure pour booster votre activité.",
    details: "Nous concevons des applications modernes, maintenables et adaptées à vos processus métier, de l'idée initiale jusqu'à la mise en production.",
    features: ["Sites web professionnels", "Applications métier", "Applications mobiles", "Maintenance évolutive"],
    process: ["Analyse du besoin", "Conception UX/UI", "Développement agile", "Déploiement et suivi"],
    badges: ["Web", "Mobile", "Plateformes", "Maintenance"],
    iconColor: "text-accent",
    iconBg: "bg-accent/20",
    badgeClass: "border-accent/40 text-accent",
    hoverBorder: "hover:border-accent/60",
    hoverShadow: "hover:shadow-accent/15",
  },
  {
    id: "infrastructure",
    iconKey: "network",
    title: "Infrastructure, Réseaux & Cloud",
    description: "Réseaux, serveurs, cloud, DevOps et supervision pour une IT performante et sécurisée.",
    details: "Nous construisons et modernisons votre socle technique pour garantir disponibilité, performance et évolutivité.",
    features: ["Architecture réseau", "Serveurs et virtualisation", "Cloud et DevOps", "Supervision 24/7"],
    process: ["Audit technique", "Plan d'architecture", "Migration ou déploiement", "Monitoring continu"],
    badges: ["Réseaux", "Cloud", "DevOps", "Supervision"],
    iconColor: "text-blue-400",
    iconBg: "bg-blue-400/20",
    badgeClass: "border-blue-400/40 text-blue-400",
    hoverBorder: "hover:border-blue-400/60",
    hoverShadow: "hover:shadow-blue-400/15",
  },
  {
    id: "security",
    iconKey: "shield",
    title: "Sécurité, Contrôle & Surveillance",
    description: "Cybersécurité, audit, contrôle d'accès et surveillance pour protéger vos données.",
    details: "Nous renforçons la protection de vos systèmes, de vos locaux et de vos données avec une approche préventive et opérationnelle.",
    features: ["Audit de sécurité", "Protection des accès", "Surveillance vidéo", "Sensibilisation des équipes"],
    process: ["Cartographie des risques", "Priorisation des actions", "Mise en conformité", "Suivi et amélioration"],
    badges: ["Cybersécurité", "Audit", "Contrôle", "Caméras"],
    iconColor: "text-green-400",
    iconBg: "bg-green-400/20",
    badgeClass: "border-green-400/40 text-green-400",
    hoverBorder: "hover:border-green-400/60",
    hoverShadow: "hover:shadow-green-400/15",
  },
  {
    id: "training",
    iconKey: "teacher",
    title: "Formation & Conseil IT",
    description: "Formations et accompagnement pour accélérer votre transformation digitale.",
    details: "Nous aidons vos équipes à monter en compétence avec des formations pratiques et du conseil adapté à votre contexte.",
    features: ["Formations IT", "Coaching technique", "Conseil transformation digitale", "Ateliers sur mesure"],
    process: ["Diagnostic des compétences", "Programme adapté", "Sessions pratiques", "Évaluation des acquis"],
    badges: ["Formation", "Conseil", "Transformation"],
    iconColor: "text-purple-400",
    iconBg: "bg-purple-400/20",
    badgeClass: "border-purple-400/40 text-purple-400",
    hoverBorder: "hover:border-purple-400/60",
    hoverShadow: "hover:shadow-purple-400/15",
  },
];

export const blogArticles = [
  {
    id: "tendances-it-2025",
    title: "Les tendances IT à surveiller en 2025",
    category: "Tendances",
    date: "15 Avril 2025",
    description: "IA générative, edge computing, cybersécurité post-quantique - découvrez ce qui va transformer le secteur IT cette année.",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80",
    categoryColor: "text-accent border-accent/40",
    content: [
      "Les organisations accélèrent leur transformation numérique autour de l'automatisation, de la donnée et de la sécurité.",
      "L'IA générative devient un outil de productivité concret pour les équipes support, commerciales, techniques et administratives.",
      "La cybersécurité reste une priorité, avec une attention particulière sur la protection des accès, la sauvegarde et la surveillance continue.",
    ],
  },
  {
    id: "securiser-infrastructure",
    title: "Comment sécuriser son infrastructure en 5 étapes",
    category: "Cybersécurité",
    date: "02 Mars 2025",
    description: "Un guide pratique pour auditer, protéger et surveiller votre système d'information contre les cybermenaces actuelles.",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=600&q=80",
    categoryColor: "text-blue-400 border-blue-400/40",
    content: [
      "La première étape consiste à inventorier les actifs critiques : serveurs, postes, applications, accès et sauvegardes.",
      "Il faut ensuite corriger les vulnérabilités prioritaires, appliquer les mises à jour et renforcer les mots de passe.",
      "Une surveillance régulière permet de détecter rapidement les incidents et de réduire leur impact sur l'activité.",
    ],
  },
  {
    id: "migration-cloud",
    title: "Migration vers le cloud : par où commencer ?",
    category: "Cloud",
    date: "18 Février 2025",
    description: "Les étapes clés, les pièges à éviter et les meilleures pratiques pour réussir votre migration cloud sans interruption de service.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    categoryColor: "text-green-400 border-green-400/40",
    content: [
      "Une migration cloud réussie commence par une analyse des applications, des dépendances et des contraintes métier.",
      "Le choix de l'architecture doit tenir compte du coût, de la performance, de la sécurité et de la capacité d'évolution.",
      "La migration doit être progressive, testée et documentée pour éviter les interruptions de service.",
    ],
  },
  {
    id: "devops-cycle-developpement",
    title: "DevOps : accélérez votre cycle de développement",
    category: "DevOps",
    date: "05 Janvier 2025",
    description: "CI/CD, Docker, Kubernetes - comment intégrer les pratiques DevOps pour livrer plus vite et mieux.",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=600&q=80",
    categoryColor: "text-purple-400 border-purple-400/40",
    content: [
      "Le DevOps rapproche développement et exploitation pour réduire les délais entre une idée et sa mise en production.",
      "L'intégration continue améliore la qualité du code grâce aux tests automatisés et aux déploiements répétables.",
      "Une bonne culture DevOps repose aussi sur la collaboration, la documentation et la mesure continue.",
    ],
  },
  {
    id: "ia-entreprises",
    title: "L'IA au service des entreprises : cas concrets",
    category: "Intelligence Artificielle",
    date: "20 Décembre 2024",
    description: "Automatisation, analyse prédictive, chatbots - comment les entreprises utilisent l'IA pour gagner en efficacité.",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=600&q=80",
    categoryColor: "text-accent border-accent/40",
    content: [
      "L'IA peut automatiser des tâches répétitives comme la classification de demandes, la génération de documents ou l'analyse de données.",
      "Les chatbots améliorent la disponibilité du support client lorsque leurs réponses sont cadrées et connectées aux bonnes sources.",
      "Les meilleurs projets IA commencent par un cas d'usage simple, mesurable et directement utile aux équipes.",
    ],
  },
  {
    id: "reseaux-entreprise",
    title: "Réseaux d'entreprise : fibre, Wi-Fi 6 ou SD-WAN ?",
    category: "Réseaux",
    date: "10 Novembre 2024",
    description: "Comparatif des solutions réseau modernes pour choisir l'infrastructure la plus adaptée à votre organisation.",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80",
    categoryColor: "text-blue-400 border-blue-400/40",
    content: [
      "Le bon choix réseau dépend du nombre d'utilisateurs, de la criticité des applications et de la répartition des sites.",
      "La fibre apporte un socle stable, le Wi-Fi 6 améliore les usages internes et le SD-WAN optimise les connexions multi-sites.",
      "Une infrastructure réseau fiable doit être documentée, supervisée et sécurisée dès sa conception.",
    ],
  },
];

export const formationCategories = [
  {
    id: "development",
    label: "Développement",
    color: "text-accent",
    bg: "bg-accent/15",
    border: "border-accent/30",
    formations: [
      { id: "web-mobile", iconKey: "laptop-code", title: "Développement Web & Mobile", tags: ["HTML", "CSS", "JavaScript", "React", "Node.js"] },
      { id: "python-django", iconKey: "python", title: "Python & Django", tags: ["Python", "Django", "REST API", "Automatisation"] },
      { id: "databases", iconKey: "database", title: "Bases de données & MongoDB", tags: ["SQL", "MongoDB", "PostgreSQL", "NoSQL"] },
    ],
  },
  {
    id: "infrastructure-security",
    label: "Infrastructure & Sécurité",
    color: "text-accent",
    bg: "bg-accent/15",
    border: "border-accent/30",
    formations: [
      { id: "cybersecurity", iconKey: "shield", title: "Cybersécurité & Ethical Hacking", tags: ["Pentesting", "ISO 27001", "Audit", "SIEM"] },
      { id: "cloud-devops", iconKey: "cloud", title: "Cloud & DevOps", tags: ["AWS", "Docker", "Kubernetes", "CI/CD"] },
      { id: "network", iconKey: "network", title: "Réseaux & Infrastructure IT", tags: ["Cisco", "VLAN", "VPN", "Routing"] },
    ],
  },
  {
    id: "support-office",
    label: "Support & Bureautique",
    color: "text-accent",
    bg: "bg-accent/15",
    border: "border-accent/30",
    formations: [
      { id: "helpdesk", iconKey: "headset", title: "Support IT & Helpdesk", tags: ["Windows", "Linux", "Dépannage", "ITIL"] },
      { id: "office", iconKey: "file", title: "Bureautique & Productivité", tags: ["Word", "Excel", "PowerPoint", "Google Workspace"] },
      { id: "systems", iconKey: "server", title: "Administration Systèmes", tags: ["Windows Server", "Linux", "Active Directory", "VMware"] },
    ],
  },
  {
    id: "ai",
    label: "Intelligence Artificielle",
    color: "text-accent",
    bg: "bg-accent/15",
    border: "border-accent/30",
    formations: [
      { id: "ai-ml", iconKey: "brain", title: "Intelligence Artificielle & Machine Learning", tags: ["Python", "TensorFlow", "Scikit-learn", "Data Science"] },
      { id: "generative-ai", iconKey: "robot", title: "IA Générative & Prompt Engineering", tags: ["ChatGPT", "Midjourney", "LangChain", "RAG", "GPT-4"] },
      { id: "ai-tools", iconKey: "laptop-code", title: "Outils IA pour développeurs", tags: ["GitHub Copilot", "Cursor", "Claude Code", "Bolt", "v0"] },
    ],
  },
  {
    id: "design",
    label: "Design & Infographie",
    color: "text-accent",
    bg: "bg-accent/15",
    border: "border-accent/30",
    formations: [
      { id: "graphic-design", iconKey: "paint", title: "Infographie & Design Graphique", tags: ["Photoshop", "Illustrator", "Canva", "InDesign"] },
      { id: "ui-ux", iconKey: "laptop-code", title: "UI/UX Design", tags: ["Figma", "Prototype", "Wireframe", "Design System"] },
    ],
  },
];

export const contactInfo = [
  { id: "email", iconKey: "email", label: "Email", value: "contact@silicontchad.com", href: "mailto:contact@silicontchad.com" },
  { id: "phone", iconKey: "phone", label: "Téléphone", value: "+235 66 05 05 43 / 60 60 52 51", href: "tel:+23566050543" },
  { id: "address", iconKey: "map", label: "Adresse", value: "N'Djamena, Tchad", href: "#" },
];
